# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 14]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Test node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: wget "https://www.foundationdb.org/downloads/6.3.12/ubuntu/installers/foundationdb-clients_6.3.12-1_amd64.deb"
    - run: sudo dpkg -i foundationdb-clients_6.3.12-1_amd64.deb
    - run: wget "https://www.foundationdb.org/downloads/6.2.28/ubuntu/installers/foundationdb-server_6.3.12-1_amd64.deb"
    - run: sudo dpkg -i foundationdb-server_6.3.12-1_amd64.deb

    - run: yarn
    - run: yarn test
